#!/usr/bin/env python3
"""Build deterministic route bundles from the audited CSS source modules."""

from __future__ import annotations

import argparse
import gzip
import json
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
CSS_ROOT = ROOT / "site" / "assets" / "css"
DESIGN_BASELINES_PATH = ROOT / "DESIGN-BASELINES.json"
REDUCED_MOTION_RE = re.compile(
    r"@media\s*\(\s*prefers-reduced-motion\s*:\s*reduce\s*\)",
    re.I,
)
NAV_SPECTRUM_KEYFRAMES_RE = re.compile(r"@keyframes\s+navSpectrumOutline\b", re.I)

SHELL = [
    "tokens.css",
    "base.css",
    "glass.css",
    "nav.css",
    "reset-shell.css",
    "cora.css",
]

SUPPORT_SHELL = [
    "tokens.css",
    "base.css",
    "glass.css",
    "nav.css",
    "nav-rainbow.css",
    "reset-shell.css",
    "cora.css",
]

BUNDLES = {
    "site-shell.bundle.css": SHELL,
    "home.bundle.css": SHELL
    + [
        "home-hero.css",
        "trust-liquid.css",
        "home-conversion.css",
        "audit-enhancements.css",
        "home-polish.css",
        "home-golden.css",
        "home-services-grid.css",
        "trust-note.css",
        "partners.css",
        "home-spacing.css",
        "typography-refinement.css",
        # WordPress previously enqueued this at wp_head after the static CSS.
        # Keep it last to preserve the approved homepage cascade exactly.
        "nav-rainbow.css",
    ],
    "it-support.bundle.css": SUPPORT_SHELL
    + [
        "it-support.css",
        "it-support-extras.css",
    ],
}

MAX_GZIP_BYTES = {
    "site-shell.bundle.css": 16_000,
    "home.bundle.css": 45_000,
    "it-support.bundle.css": 30_000,
}


def render(name: str, sources: list[str]) -> bytes:
    chunks = [
        "/* Generated by tools/build-css.py. Edit source modules, not this file. */\n"
    ]
    for source_name in sources:
        source_path = CSS_ROOT / source_name
        if not source_path.is_file():
            raise FileNotFoundError(f"Missing CSS source: {source_path}")
        chunks.append(f"\n/* source: {source_name} */\n")
        chunks.append(source_path.read_text(encoding="utf-8").rstrip())
        chunks.append("\n")
    return "".join(chunks).encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when a committed bundle is stale",
    )
    args = parser.parse_args()

    failures: list[str] = []
    baselines: dict = {}
    try:
        baselines = json.loads(DESIGN_BASELINES_PATH.read_text(encoding="utf-8"))
    except FileNotFoundError:
        failures.append(f"required design baseline is missing: {DESIGN_BASELINES_PATH}")
    except (OSError, json.JSONDecodeError) as exc:
        failures.append(f"invalid design baseline {DESIGN_BASELINES_PATH}: {exc}")

    if not isinstance(baselines, dict) or baselines.get("version") != 1:
        failures.append("DESIGN-BASELINES.json must be a version 1 JSON object")
        baselines = {}

    registered_home_sources = baselines.get("home_bundle_sources")
    if registered_home_sources != BUNDLES["home.bundle.css"]:
        failures.append(
            "home.bundle.css source order differs from DESIGN-BASELINES.json"
        )

    nav_spectrum_source = CSS_ROOT / "nav-rainbow.css"
    if nav_spectrum_source.is_file():
        nav_spectrum_text = nav_spectrum_source.read_text(encoding="utf-8")
        if not NAV_SPECTRUM_KEYFRAMES_RE.search(nav_spectrum_text):
            failures.append("nav-rainbow.css is missing navSpectrumOutline")
        if not REDUCED_MOTION_RE.search(nav_spectrum_text):
            failures.append("nav-rainbow.css is missing reduced-motion coverage")

    for name, sources in BUNDLES.items():
        output = CSS_ROOT / name
        expected = render(name, sources)
        expected_text = expected.decode("utf-8")
        if "@keyframes" in expected_text and not REDUCED_MOTION_RE.search(expected_text):
            failures.append(f"{name} contains animation without route-level reduced-motion coverage")
        compressed_size = len(gzip.compress(expected, compresslevel=9, mtime=0))
        if compressed_size > MAX_GZIP_BYTES[name]:
            failures.append(
                f"{name} is {compressed_size} gzip bytes; budget is {MAX_GZIP_BYTES[name]}"
            )

        if args.check:
            if not output.is_file() or output.read_bytes() != expected:
                failures.append(f"stale or missing generated bundle: {output}")
        else:
            output.write_bytes(expected)
            print(
                f"built {output.relative_to(ROOT)} "
                f"({len(expected)} bytes, {compressed_size} gzip bytes)"
            )

    if failures:
        for failure in failures:
            print(f"ERROR: {failure}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
